### ISSUE TITLE
关于项目一些问题

### ISSUE THREAD

**Issue by zxb-0** [Auromix/ROS-LLM#1]
你好。感谢您的工作
1.请问这个项目可以在虚拟机上运行嘛
2.他需要我的设备有GPU吗
3.我用的neotic，我看您在更新中，请问这个项目可以直接跑在neotic上吗

**Comment by Hermanye996** [comment]
你好
1.未在虚拟机下进行测试，但应该没有和硬件相关的依赖包，你可以尝试以下
2.不需要有GPU设备，但如果使用Whisper等包，你需要考虑这些包的依赖性
3.noetic目前尚未更新，如果我有精力的话会维护ROS1版本的，我预计在2024 Q1更新一个新的多模态的框架，应该会有ROS1的相关支持
