### ISSUE TITLE
Package not found Issue

### ISSUE THREAD

**Issue by chad-yao** [Auromix/ROS-LLM#2]
Hi, @Hermanye996 , great work. 
Here is my issue.
While running `ros2 launch llm_bringup chatgpt_with_turtle_robot.launch.py`, I got Package 'llm_bringup' not found: "package 'llm_bringup' not found, searching: ['/root/ros2_humble/install/rqt_bag_plugins' ...]. Do you have any suggestions?

**Comment by Hermanye996** [comment]
Hi, @Dominique-Yiu 
Please try `echo "source <your_ros2_workspace_absolute_path>/install/setup.bash" >> ~/.bashrc` and `echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc`.

**Comment by chad-yao** [comment]
Thanks, it works
