### ISSUE TITLE
Errors after ros2 topic pub

### ISSUE THREAD

**Issue by acoudgo** [Auromix/ROS-LLM#3]
an error occured after ros2  launch llm_bringup chatgpt_with_turtle_robot.launch.py

[ERROR] [chatgpt-2]: process has died [pid 132666, exit code 1, cmd '/opt/ros/foxy/llm_ws/install/llm_model/lib/llm_model/chatgpt --ros-args -r __node:=chatgpt'].

an error occured after "" ros2 topic pub /llm_state std_msgs/msg/String "data: 'listening'" -1 "" not until audio recording finished

[ERROR] [llm_audio_input-1]: process has died [pid 132664, exit code 1, cmd '/opt/ros/foxy/llm_ws/install/llm_input/lib/llm_input/llm_audio_input --ros-args -r __node:=llm_audio_input'].

**Comment by Hermanye996** [comment]
Could you provide more debug information? @acoudgo

**Comment by acoudgo** [comment]
I am not sure if it is cause of ubuntu 20.04, but it is also supportive for ROS 2 HUMBLE written in ROS official website, and the installation is successful. I will try it later, anyway. TXS.

**Comment by Hermanye996** [comment]
The ROS-LLM package utilizes a simplified ROS2 syntax, and it should be compatible with ROS2 Foxy on Ubuntu 20.04 (although it has not been tested—feel free to give it a try). Using ROS 2 Humble from source on Ubuntu 20.04 has not been tested. @acoudgo
