### ISSUE TITLE
2 packages had stderr output: ur_kinematics ur_robot_driver

### ISSUE THREAD

**Issue by Yxxxhu** [Auromix/ROS-LLM#4]
]

**Comment by Yxxxhu** [comment]
Package 'llm_bringup' not found: "package 'llm_bringup' not found

**Comment by Hermanye996** [comment]
```text
Package 'llm_bringup' not found: "package 'llm_bringup' not found
```
Please Check your workspace env settings

**Comment by Hermanye996** [comment]
```text
When Build the Workspace through colcon build --symlink-install

2 packages had stderr output: ur_kinematics ur_robot_driver

is showing as result.

How to solve it.
```
"ur_kinematics" and "ur_robot_driver" are likely related to your UR robotic arm and are unrelated to "ros-llm". You may need to reorganize the contents of your workspace.

**Comment by Yxxxhu** [comment]
Thanks for your support. However, I have checked and tried. This still not work.
What should I do to add the env settings.

![Screenshot from 2024-01-25 21-37-59](https://github.com/Auromix/ROS-LLM/assets/46534173/3c6e37da-f99f-4407-a5af-ab5baafb195c)

**Comment by Hermanye996** [comment]
It seems that your `ros workspace` has not been built and the `llm_bringup` function package cannot be found. This should be caused by your bash environment settings. Please refer to this blog https://blog.csdn.net/m0_56661101/article/details/134098153?spm=1001.2014.3001.5502
