### ISSUE TITLE
openai.RateLimitError

### ISSUE THREAD

**Issue by Fayhao** [Auromix/ROS-LLM#7]
when I sent messages to OpenAI: [{'role': 'system', 'content': ''}, it showed that 
 [chatgpt-2] openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
[ERROR] [chatgpt-2]: process has died [pid 8808, exit code 1, cmd '/home/fay/ros2_ws/install/llm_model/lib/llm_model/chatgpt --ros-args -r __node:=chatgpt'].
but when I chack my api, it was never used?

**Comment by Hermanye996** [comment]
You have surpassed your current usage limit. Please review your plan and billing information. Verify your OpenAI API key; if issues persist, consider updating your account settings.

**Comment by Fayhao** [comment]
Actually, it's the first time I export the api key, and I wonder if this means that my openai key has expired? And how can I do next?
![image](https://github.com/Auromix/ROS-LLM/assets/102647612/ee0a202e-1fb0-4415-9690-145da04cd46e)

**Comment by imadh** [comment]
Hi @SuccuFy, you can see on the provided screenshot that your credit expired, so you need to add more credit to be able to use the OpenAI API.

**Comment by Fayhao** [comment]
> Hi @SuccuFy, you can see on the provided screenshot that your credit expired, so you need to add more credit to be able to use the OpenAI API.

Thank you! Finally, I chose an open resource free plan, and it works!
